FROM node:16
MAINTAINER prajakta-upgrad
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package*.json ./
COPY . .
RUN CI=true
# Installs all node packages
RUN npm install
RUN npm run build
# Bundle app source
EXPOSE 8080
CMD [ "node", "server.js" ]